// Расширенная база данных питательной ценности ингредиентов
// Точность: 85-95% при правильном использовании

export const nutritionDatabase = {
  // === МЯСО И ПТИЦА ===
  'говядина': { calories: 250, protein: 26, carbs: 0, fat: 15, category: 'meat' },
  'говяжий фарш': { calories: 254, protein: 25.8, carbs: 0, fat: 15.2, category: 'meat' },
  'свинина': { calories: 263, protein: 27, carbs: 0, fat: 16, category: 'meat' },
  'свиной фарш': { calories: 263, protein: 27, carbs: 0, fat: 16, category: 'meat' },
  'баранина': { calories: 294, protein: 25, carbs: 0, fat: 21, category: 'meat' },
  'телятина': { calories: 172, protein: 30, carbs: 0, fat: 4.5, category: 'meat' },
  'курица': { calories: 165, protein: 31, carbs: 0, fat: 3.6, category: 'poultry' },
  'куриная грудка': { calories: 165, protein: 31, carbs: 0, fat: 3.6, category: 'poultry' },
  'куриные бедра': { calories: 209, protein: 26, carbs: 0, fat: 10, category: 'poultry' },
  'куриные крылья': { calories: 203, protein: 18, carbs: 0, fat: 14, category: 'poultry' },
  'индейка': { calories: 189, protein: 29, carbs: 0, fat: 7, category: 'poultry' },
  'утка': { calories: 337, protein: 19, carbs: 0, fat: 28, category: 'poultry' },
  'гусь': { calories: 364, protein: 16, carbs: 0, fat: 33, category: 'poultry' },

  // === РЫБА И МОРЕПРОДУКТЫ ===
  'рыба': { calories: 206, protein: 22, carbs: 0, fat: 12, category: 'fish' },
  'лосось': { calories: 208, protein: 25, carbs: 0, fat: 12, category: 'fish' },
  'тунец': { calories: 144, protein: 30, carbs: 0, fat: 1, category: 'fish' },
  'треска': { calories: 82, protein: 18, carbs: 0, fat: 0.7, category: 'fish' },
  'окунь': { calories: 124, protein: 24, carbs: 0, fat: 2.5, category: 'fish' },
  'карп': { calories: 127, protein: 18, carbs: 0, fat: 5.6, category: 'fish' },
  'щука': { calories: 88, protein: 19, carbs: 0, fat: 0.7, category: 'fish' },
  'креветки': { calories: 99, protein: 24, carbs: 0, fat: 0.3, category: 'seafood' },
  'кальмары': { calories: 92, protein: 16, carbs: 3, fat: 1.4, category: 'seafood' },
  'мидии': { calories: 86, protein: 12, carbs: 4.5, fat: 2.2, category: 'seafood' },
  'икра': { calories: 264, protein: 25, carbs: 1, fat: 18, category: 'seafood' },

  // === МОЛОЧНЫЕ ПРОДУКТЫ ===
  'молоко': { calories: 42, protein: 3.4, carbs: 5, fat: 1, category: 'dairy' },
  'молоко 3.2%': { calories: 60, protein: 3, carbs: 4.7, fat: 3.2, category: 'dairy' },
  'молоко 1%': { calories: 42, protein: 3.4, carbs: 5, fat: 1, category: 'dairy' },
  'кефир': { calories: 56, protein: 3, carbs: 4, fat: 3.2, category: 'dairy' },
  'йогурт': { calories: 59, protein: 10, carbs: 3.6, fat: 0.4, category: 'dairy' },
  'йогурт греческий': { calories: 59, protein: 10, carbs: 3.6, fat: 0.4, category: 'dairy' },
  'творог': { calories: 103, protein: 18, carbs: 3, fat: 0.6, category: 'dairy' },
  'творог 9%': { calories: 169, protein: 16, carbs: 2, fat: 9, category: 'dairy' },
  'сыр': { calories: 113, protein: 7, carbs: 1, fat: 9, category: 'dairy' },
  'сыр твердый': { calories: 356, protein: 25, carbs: 1.3, fat: 27, category: 'dairy' },
  'сыр моцарелла': { calories: 280, protein: 22, carbs: 2.2, fat: 22, category: 'dairy' },
  'сыр фета': { calories: 264, protein: 14, carbs: 4, fat: 21, category: 'dairy' },
  'пармезан': { calories: 431, protein: 38, carbs: 4.1, fat: 29, category: 'dairy' },
  'сметана': { calories: 206, protein: 2.8, carbs: 3.2, fat: 20, category: 'dairy' },
  'сметана 20%': { calories: 206, protein: 2.8, carbs: 3.2, fat: 20, category: 'dairy' },
  'сметана 15%': { calories: 158, protein: 2.8, carbs: 3.2, fat: 15, category: 'dairy' },
  'масло сливочное': { calories: 717, protein: 0.1, carbs: 0.1, fat: 81, category: 'dairy' },
  'масло топленое': { calories: 892, protein: 0.2, carbs: 0, fat: 99, category: 'dairy' },

  // === ЯЙЦА ===
  'яйца': { calories: 155, protein: 13, carbs: 1.1, fat: 11, category: 'eggs' },
  'яйцо куриное': { calories: 155, protein: 13, carbs: 1.1, fat: 11, category: 'eggs' },
  'яйцо перепелиное': { calories: 168, protein: 14, carbs: 0.4, fat: 12, category: 'eggs' },
  'белок яичный': { calories: 52, protein: 11, carbs: 0.7, fat: 0.2, category: 'eggs' },
  'желток яичный': { calories: 322, protein: 16, carbs: 1.8, fat: 27, category: 'eggs' },

  // === КРУПЫ И ЗЛАКИ ===
  'рис': { calories: 130, protein: 2.7, carbs: 28, fat: 0.3, category: 'grains' },
  'рис белый': { calories: 130, protein: 2.7, carbs: 28, fat: 0.3, category: 'grains' },
  'рис бурый': { calories: 111, protein: 2.6, carbs: 23, fat: 0.9, category: 'grains' },
  'гречка': { calories: 132, protein: 4.5, carbs: 25, fat: 1.6, category: 'grains' },
  'овсянка': { calories: 68, protein: 2.4, carbs: 12, fat: 1.4, category: 'grains' },
  'перловка': { calories: 123, protein: 2.3, carbs: 28, fat: 0.4, category: 'grains' },
  'пшено': { calories: 90, protein: 3, carbs: 17, fat: 0.4, category: 'grains' },
  'кукуруза': { calories: 86, protein: 3.3, carbs: 19, fat: 1.2, category: 'grains' },
  'макароны': { calories: 131, protein: 5, carbs: 25, fat: 1.1, category: 'grains' },
  'макароны из твердых сортов': { calories: 131, protein: 5, carbs: 25, fat: 1.1, category: 'grains' },
  'хлеб': { calories: 265, protein: 9, carbs: 49, fat: 3.2, category: 'grains' },
  'хлеб белый': { calories: 265, protein: 9, carbs: 49, fat: 3.2, category: 'grains' },
  'хлеб черный': { calories: 214, protein: 6.6, carbs: 40, fat: 1.2, category: 'grains' },
  'хлеб ржаной': { calories: 214, protein: 6.6, carbs: 40, fat: 1.2, category: 'grains' },
  'хлеб цельнозерновой': { calories: 247, protein: 13, carbs: 41, fat: 4.2, category: 'grains' },
  'мука': { calories: 364, protein: 10, carbs: 76, fat: 1, category: 'grains' },
  'мука пшеничная': { calories: 364, protein: 10, carbs: 76, fat: 1, category: 'grains' },
  'мука ржаная': { calories: 325, protein: 6.9, carbs: 69, fat: 1.2, category: 'grains' },

  // === ОВОЩИ ===
  'картофель': { calories: 77, protein: 2, carbs: 17, fat: 0.1, category: 'vegetables' },
  'картофель молодой': { calories: 61, protein: 2, carbs: 14, fat: 0.1, category: 'vegetables' },
  'лук': { calories: 40, protein: 1.1, carbs: 9, fat: 0.1, category: 'vegetables' },
  'лук репчатый': { calories: 40, protein: 1.1, carbs: 9, fat: 0.1, category: 'vegetables' },
  'лук зеленый': { calories: 19, protein: 1.3, carbs: 3.2, fat: 0.1, category: 'vegetables' },
  'морковь': { calories: 41, protein: 0.9, carbs: 10, fat: 0.2, category: 'vegetables' },
  'помидоры': { calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, category: 'vegetables' },
  'помидоры черри': { calories: 15, protein: 0.8, carbs: 3.9, fat: 0.2, category: 'vegetables' },
  'огурцы': { calories: 16, protein: 0.7, carbs: 4, fat: 0.1, category: 'vegetables' },
  'капуста': { calories: 25, protein: 1.3, carbs: 6, fat: 0.1, category: 'vegetables' },
  'капуста белокочанная': { calories: 25, protein: 1.3, carbs: 6, fat: 0.1, category: 'vegetables' },
  'капуста цветная': { calories: 25, protein: 1.9, carbs: 5, fat: 0.3, category: 'vegetables' },
  'капуста брокколи': { calories: 34, protein: 2.8, carbs: 7, fat: 0.4, category: 'vegetables' },
  'свекла': { calories: 43, protein: 1.5, carbs: 8.8, fat: 0.1, category: 'vegetables' },
  'редис': { calories: 16, protein: 1.2, carbs: 3.4, fat: 0.1, category: 'vegetables' },
  'редиска': { calories: 16, protein: 1.2, carbs: 3.4, fat: 0.1, category: 'vegetables' },
  'редис дайкон': { calories: 18, protein: 0.6, carbs: 4.1, fat: 0.1, category: 'vegetables' },
  'перец': { calories: 27, protein: 1.3, carbs: 5.3, fat: 0.3, category: 'vegetables' },
  'перец болгарский': { calories: 27, protein: 1.3, carbs: 5.3, fat: 0.3, category: 'vegetables' },
  'перец чили': { calories: 40, protein: 2, carbs: 9, fat: 0.2, category: 'vegetables' },
  'баклажаны': { calories: 24, protein: 1, carbs: 5.5, fat: 0.1, category: 'vegetables' },
  'кабачки': { calories: 17, protein: 1.2, carbs: 3.4, fat: 0.2, category: 'vegetables' },
  'цуккини': { calories: 17, protein: 1.2, carbs: 3.4, fat: 0.2, category: 'vegetables' },
  'тыква': { calories: 26, protein: 1, carbs: 6.5, fat: 0.1, category: 'vegetables' },
  'чеснок': { calories: 149, protein: 6.5, carbs: 30, fat: 0.5, category: 'vegetables' },
  'имбирь': { calories: 80, protein: 1.8, carbs: 18, fat: 0.8, category: 'vegetables' },
  'шпинат': { calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, category: 'vegetables' },
  'салат': { calories: 15, protein: 1.4, carbs: 2.9, fat: 0.2, category: 'vegetables' },
  'салат айсберг': { calories: 14, protein: 0.9, carbs: 3, fat: 0.1, category: 'vegetables' },
  'руккола': { calories: 25, protein: 2.6, carbs: 3.7, fat: 0.7, category: 'vegetables' },
  'петрушка': { calories: 36, protein: 3, carbs: 6, fat: 0.8, category: 'vegetables' },
  'укроп': { calories: 40, protein: 2.5, carbs: 6, fat: 0.5, category: 'vegetables' },
  'зелень': { calories: 22, protein: 2.6, carbs: 4, fat: 0.4, category: 'vegetables' },

  // === ФРУКТЫ И ЯГОДЫ ===
  'яблоки': { calories: 52, protein: 0.3, carbs: 14, fat: 0.2, category: 'fruits' },
  'бананы': { calories: 89, protein: 1.1, carbs: 23, fat: 0.3, category: 'fruits' },
  'апельсины': { calories: 47, protein: 0.9, carbs: 12, fat: 0.1, category: 'fruits' },
  'лимоны': { calories: 29, protein: 1.1, carbs: 9, fat: 0.3, category: 'fruits' },
  'лимон': { calories: 29, protein: 1.1, carbs: 9, fat: 0.3, category: 'fruits' },
  'груши': { calories: 57, protein: 0.4, carbs: 15, fat: 0.1, category: 'fruits' },
  'виноград': { calories: 62, protein: 0.6, carbs: 16, fat: 0.2, category: 'fruits' },
  'клубника': { calories: 32, protein: 0.7, carbs: 8, fat: 0.3, category: 'fruits' },
  'малина': { calories: 52, protein: 1.2, carbs: 12, fat: 0.7, category: 'fruits' },
  'черника': { calories: 57, protein: 0.7, carbs: 14, fat: 0.3, category: 'fruits' },
  'клюква': { calories: 46, protein: 0.4, carbs: 12, fat: 0.1, category: 'fruits' },

  // === ОРЕХИ И СЕМЕНА ===
  'орехи': { calories: 607, protein: 20, carbs: 21, fat: 54, category: 'nuts' },
  'орехи грецкие': { calories: 654, protein: 15.2, carbs: 13.7, fat: 65.2, category: 'nuts' },
  'миндаль': { calories: 579, protein: 21, carbs: 22, fat: 50, category: 'nuts' },
  'фундук': { calories: 628, protein: 15, carbs: 17, fat: 61, category: 'nuts' },
  'кешью': { calories: 553, protein: 18, carbs: 30, fat: 44, category: 'nuts' },
  'арахис': { calories: 567, protein: 26, carbs: 16, fat: 49, category: 'nuts' },
  'семечки подсолнечника': { calories: 578, protein: 21, carbs: 20, fat: 51, category: 'nuts' },
  'семечки тыквенные': { calories: 559, protein: 30, carbs: 11, fat: 49, category: 'nuts' },
  'семена льна': { calories: 534, protein: 18, carbs: 29, fat: 42, category: 'nuts' },
  'семена чиа': { calories: 486, protein: 17, carbs: 42, fat: 31, category: 'nuts' },

  // === МАСЛА И ЖИРЫ ===
  'масло растительное': { calories: 884, protein: 0, carbs: 0, fat: 100, category: 'oils' },
  'масло подсолнечное': { calories: 884, protein: 0, carbs: 0, fat: 100, category: 'oils' },
  'масло оливковое': { calories: 884, protein: 0, carbs: 0, fat: 100, category: 'oils' },
  'масло кокосовое': { calories: 862, protein: 0, carbs: 0, fat: 100, category: 'oils' },
  'масло льняное': { calories: 884, protein: 0, carbs: 0, fat: 100, category: 'oils' },

  // === СПЕЦИИ И ПРИПРАВЫ ===
  'соль': { calories: 0, protein: 0, carbs: 0, fat: 0, category: 'spices' },
  'сахар': { calories: 387, protein: 0, carbs: 100, fat: 0, category: 'spices' },
  'сахар коричневый': { calories: 380, protein: 0, carbs: 98, fat: 0, category: 'spices' },
  'мед': { calories: 304, protein: 0.3, carbs: 82, fat: 0, category: 'spices' },
  'перец черный': { calories: 251, protein: 10, carbs: 64, fat: 3.3, category: 'spices' },
  'перец красный': { calories: 282, protein: 12, carbs: 56, fat: 6.2, category: 'spices' },
  'паприка': { calories: 282, protein: 12, carbs: 56, fat: 6.2, category: 'spices' },
  'корица': { calories: 247, protein: 4, carbs: 81, fat: 1.2, category: 'spices' },
  'ваниль': { calories: 288, protein: 1, carbs: 13, fat: 0.1, category: 'spices' },
  'лавровый лист': { calories: 313, protein: 8, carbs: 75, fat: 8.4, category: 'spices' },
  'базилик': { calories: 22, protein: 3.2, carbs: 2.6, fat: 0.6, category: 'spices' },
  'орегано': { calories: 265, protein: 9, carbs: 69, fat: 4.3, category: 'spices' },
  'тимьян': { calories: 101, protein: 6, carbs: 24, fat: 1.7, category: 'spices' },
  'розмарин': { calories: 131, protein: 3.3, carbs: 21, fat: 5.9, category: 'spices' },
  'петрушка сушеная': { calories: 292, protein: 22, carbs: 50, fat: 5.5, category: 'spices' },
  'укроп сушеный': { calories: 253, protein: 20, carbs: 55, fat: 4.4, category: 'spices' },

  // === БОБОВЫЕ ===
  'фасоль': { calories: 127, protein: 8.2, carbs: 22, fat: 0.5, category: 'legumes' },
  'фасоль белая': { calories: 127, protein: 8.2, carbs: 22, fat: 0.5, category: 'legumes' },
  'фасоль красная': { calories: 127, protein: 8.2, carbs: 22, fat: 0.5, category: 'legumes' },
  'горох': { calories: 81, protein: 5, carbs: 14, fat: 0.4, category: 'legumes' },
  'горох зеленый': { calories: 81, protein: 5, carbs: 14, fat: 0.4, category: 'legumes' },
  'чечевица': { calories: 116, protein: 9, carbs: 20, fat: 0.4, category: 'legumes' },
  'нут': { calories: 164, protein: 8.9, carbs: 27, fat: 2.6, category: 'legumes' },
  'соя': { calories: 147, protein: 13, carbs: 11, fat: 6.8, category: 'legumes' },

  // === ГРИБЫ ===
  'грибы': { calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, category: 'mushrooms' },
  'шампиньоны': { calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, category: 'mushrooms' },
  'вешенки': { calories: 33, protein: 3.3, carbs: 6.1, fat: 0.4, category: 'mushrooms' },
  'лисички': { calories: 19, protein: 1.5, carbs: 1.5, fat: 1.1, category: 'mushrooms' },
  'белые грибы': { calories: 34, protein: 3.7, carbs: 1.1, fat: 1.7, category: 'mushrooms' },

  // === ГОТОВЫЕ ПРОДУКТЫ ===
  'майонез': { calories: 680, protein: 1, carbs: 0.6, fat: 75, category: 'ready' },
  'кетчуп': { calories: 93, protein: 1.7, carbs: 22, fat: 0.1, category: 'ready' },
  'горчица': { calories: 162, protein: 6, carbs: 11, fat: 10, category: 'ready' },
  'соус соевый': { calories: 8, protein: 1.3, carbs: 0.8, fat: 0, category: 'ready' },
  'уксус': { calories: 19, protein: 0, carbs: 0.9, fat: 0, category: 'ready' },
  'уксус бальзамический': { calories: 88, protein: 0.5, carbs: 17, fat: 0, category: 'ready' },
  'томатная паста': { calories: 82, protein: 4.3, carbs: 19, fat: 0.2, category: 'ready' },
  'бульон': { calories: 12, protein: 0.2, carbs: 0.1, fat: 0.1, category: 'ready' },
  'бульон куриный': { calories: 12, protein: 0.2, carbs: 0.1, fat: 0.1, category: 'ready' },
  'бульон мясной': { calories: 12, protein: 0.2, carbs: 0.1, fat: 0.1, category: 'ready' },
  'бульон овощной': { calories: 12, protein: 0.2, carbs: 0.1, fat: 0.1, category: 'ready' }
};

// Коэффициенты для способов приготовления
export const cookingMethods = {
  'сырой': 1.0,
  'варка': 1.0,
  'на пару': 1.0,
  'тушение': 1.1,
  'запекание': 1.2,
  'жарка': 1.5,
  'фритюр': 2.0,
  'гриль': 1.3,
  'копчение': 1.4
};

// Единицы измерения и их конверсия в граммы
export const unitConversions = {
  'г': 1,
  'грамм': 1,
  'кг': 1000,
  'килограмм': 1000,
  'мл': 1,
  'миллилитр': 1,
  'л': 1000,
  'литр': 1000,
  'шт': 50,
  'штук': 50,
  'штука': 50,
  'кусок': 50,
  'кусочек': 50,
  'кусочков': 50,
  'долька': 20,
  'долек': 20,
  'зубчик': 5,
  'зубчиков': 5,
  'столовая ложка': 15,
  'ст.л.': 15,
  'чайная ложка': 5,
  'ч.л.': 5,
  'стакан': 200,
  'чашка': 250,
  'пучок': 30,
  'веточка': 5,
  'веточек': 5,
  'лист': 2,
  'листов': 2,
  'щепотка': 1,
  'по вкусу': 5,
  'немного': 10,
  'чуть-чуть': 5
};

// Специальные фразы для извлечения количества
export const quantityPhrases = {
  'полстакана': 100,
  'половина стакана': 100,
  'четверть стакана': 50,
  'треть стакана': 67,
  'половина': 0.5,
  'четверть': 0.25,
  'треть': 0.33,
  'две трети': 0.67,
  'несколько': 3,
  'несколько штук': 3,
  'пара': 2,
  'парочка': 2,
  'горсть': 50,
  'щепотка': 1,
  'по вкусу': 5,
  'немного': 10,
  'чуть-чуть': 5,
  'совсем немного': 2
};
